# Generated by Django 2.0.3 on 2018-04-13 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machineManage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='id',
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(db_index=True, max_length=32, primary_key=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(db_index=True, max_length=32, primary_key=True, serialize=False),
        ),
    ]
